//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera_Deportiva_Evento
    {
        public int ID { get; set; }
        public int ID_Atleta { get; set; }
        public string Prueba { get; set; }
        public string Resultado { get; set; }
        public string Fecha_Y_Lugar { get; set; }
        public string Evento { get; set; }
    }
}
