//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Atleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Datos_Atleta()
        {
            this.Alergias = new HashSet<Alergias>();
            this.Anexos = new HashSet<Anexos>();
            this.Aparato_Locomotor = new HashSet<Aparato_Locomotor>();
            this.Apoyo_Economico = new HashSet<Apoyo_Economico>();
            this.Atleta_Categoria = new HashSet<Atleta_Categoria>();
            this.Carrera_Deportiva = new HashSet<Carrera_Deportiva>();
            this.Carrera_Deportiva_Evento = new HashSet<Carrera_Deportiva_Evento>();
            this.Carrera_Deportiva_Familiar = new HashSet<Carrera_Deportiva_Familiar>();
            this.Condiciones_Clinicas_Actuales_Principal = new HashSet<Condiciones_Clinicas_Actuales_Principal>();
            this.Consiste_Apoyo = new HashSet<Consiste_Apoyo>();
            this.Educacion = new HashSet<Educacion>();
            this.Equipo_Deportivo = new HashSet<Equipo_Deportivo>();
            this.Examen_Fisico_Principal = new HashSet<Examen_Fisico_Principal>();
            this.Ficha_Antropometrica = new HashSet<Ficha_Antropometrica>();
            this.Habitacion = new HashSet<Habitacion>();
            this.Habitos = new HashSet<Habitos>();
            this.Historia_Familiar = new HashSet<Historia_Familiar>();
            this.Historial_Medico = new HashSet<Historial_Medico>();
            this.Informacion_Familiar = new HashSet<Informacion_Familiar>();
            this.Medicamentos = new HashSet<Medicamentos>();
            this.Situacion_Laboral = new HashSet<Situacion_Laboral>();
        }
    
        public int ID { get; set; }
        public string Foto { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<System.DateTime> Fecha_De_Registro { get; set; }
        public string Genero { get; set; }
        public string Numero_De_Cedula { get; set; }
        public string Correo_Electronico { get; set; }
        public string Telefono_Convencional { get; set; }
        public string Telefono_Celular { get; set; }
        public string Tiene_Seguro { get; set; }
        public int Hospital { get; set; }
        public string Dirreccion { get; set; }
        public int Municipio { get; set; }
        public string Nombre_Madre { get; set; }
        public string Telefono_Madre { get; set; }
        public string Nombre_Padre { get; set; }
        public string Telefono_Padre { get; set; }
        public string Emergencia { get; set; }
        public string Dirreccion_Emergencia { get; set; }
        public string Embarazo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alergias> Alergias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anexos> Anexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aparato_Locomotor> Aparato_Locomotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apoyo_Economico> Apoyo_Economico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atleta_Categoria> Atleta_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrera_Deportiva> Carrera_Deportiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrera_Deportiva_Evento> Carrera_Deportiva_Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrera_Deportiva_Familiar> Carrera_Deportiva_Familiar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Condiciones_Clinicas_Actuales_Principal> Condiciones_Clinicas_Actuales_Principal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consiste_Apoyo> Consiste_Apoyo { get; set; }
        public virtual Hospital Hospital1 { get; set; }
        public virtual Municipio Municipio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Educacion> Educacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo_Deportivo> Equipo_Deportivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen_Fisico_Principal> Examen_Fisico_Principal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ficha_Antropometrica> Ficha_Antropometrica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitacion> Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitos> Habitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia_Familiar> Historia_Familiar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Medico> Historial_Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informacion_Familiar> Informacion_Familiar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamentos> Medicamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Situacion_Laboral> Situacion_Laboral { get; set; }
    }
}
