//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_Deportivo
    {
        public int ID { get; set; }
        public int ID_Atleta { get; set; }
        public string equipdep { get; set; }
        public string relaentre { get; set; }
        public string relacompa { get; set; }
        public string ra_ina_entre { get; set; }
        public string ra_ina_compa { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Datos_Atleta Datos_Atleta { get; set; }
    }
}
