//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examenes
    {
        public int ID { get; set; }
        public int ID_Condiciones_Clinicas_Actuales { get; set; }
        public int ID_Examen_Fisico { get; set; }
        public int ID_Ficha_Antropometrica { get; set; }
    }
}
