//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen_Fisico_Principal
    {
        public int ID { get; set; }
        public int ID_Atleta { get; set; }
        public int ID_Examen_Fisico { get; set; }
        public string Normal { get; set; }
        public string Hallazgos_Anormales { get; set; }
    
        public virtual Datos_Atleta Datos_Atleta { get; set; }
        public virtual Examen_Fisico Examen_Fisico { get; set; }
    }
}
