//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha_Antropometrica
    {
        public int ID { get; set; }
        public int ID_Atleta { get; set; }
        public string Nombre_Y_Apellidos { get; set; }
        public int Evaluacion { get; set; }
        public System.DateTime Fecha_De_Evaluacion { get; set; }
        public string Sexo { get; set; }
        public System.DateTime Fecha_De_Nacimiento { get; set; }
        public string Menstruacion { get; set; }
        public string Antropometrista { get; set; }
        public string Anotador { get; set; }
        public string Txt_Ficha_Antropometrica { get; set; }
        public decimal Toma1 { get; set; }
        public decimal Toma2 { get; set; }
        public decimal Toma3 { get; set; }
        public decimal Promedio_Mediana { get; set; }
        public Nullable<System.DateTime> Fecha_de_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_de_Actualizacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Datos_Atleta Datos_Atleta { get; set; }
    }
}
