//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string Contraseña { get; set; }
        [Required(ErrorMessage = "Este campo es requerido")]
        public string Correo { get; set; }
        public Nullable<int> ID_Rol { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Role Role { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
